#ifndef _LOADCODE_H_
#define _LOADCODE_H_

#define ENTRY                   extern char
#define ENTRY_TO_VALUE(entry)   ((int)(&entry))

ENTRY BASE_LADDR;

ENTRY VECTOR_SIZE;
ENTRY VECTOR_ADDR;
ENTRY VECTOR_LADDR;

ENTRY SYSTEM_SIZE;
ENTRY SYSTEM_ADDR;
ENTRY SYSTEM_LADDR;

ENTRY SRAM0_SIZE;
ENTRY SRAM0_ADDR;
ENTRY SRAM0_LADDR;

ENTRY DATA_SIZE;
ENTRY DATA_ADDR;
ENTRY DATA_LADDR;

ENTRY LOAD_SIZE;

ENTRY BSS_ADDR;
ENTRY BSS_SIZE;

ENTRY STACK_ADDR;
ENTRY STACK_SIZE;

ENTRY SRAM1_LADDR;
ENTRY SRAM1_ADDR;
ENTRY SRAM1_SIZE;

ENTRY SRAM2_LADDR;
ENTRY SRAM2_ADDR;
ENTRY SRAM2_SIZE;

ENTRY BANK_LADDR;
ENTRY BANK_ADDR;
ENTRY BANK_SIZE;

ENTRY PARAM_ADDR;

#define BASE_FLASH_ADDR     ENTRY_TO_VALUE(BASE_LADDR)

#define VECTOR_SIZE         ENTRY_TO_VALUE(VECTOR_SIZE)
#define VECTOR_RAM_ADDR     ENTRY_TO_VALUE(VECTOR_ADDR)
#define VECTOR_FLASH_ADDR   (ENTRY_TO_VALUE(VECTOR_LADDR) + BASE_FLASH_ADDR)

#define SYSTEM_SIZE         ENTRY_TO_VALUE(SYSTEM_SIZE)
#define SYSTEM_RAM_ADDR     ENTRY_TO_VALUE(SYSTEM_ADDR)
#define SYSTEM_FLASH_ADDR   (ENTRY_TO_VALUE(SYSTEM_LADDR) + BASE_FLASH_ADDR)

#define SRAM0_SIZE          ENTRY_TO_VALUE(SRAM0_SIZE)
#define SRAM0_RAM_ADDR      ENTRY_TO_VALUE(SRAM0_ADDR)
#define SRAM0_FLASH_ADDR    (ENTRY_TO_VALUE(SRAM0_LADDR) +  BASE_FLASH_ADDR)

#define DATA_SIZE           ENTRY_TO_VALUE(DATA_SIZE)
#define DATA_RAM_ADDR       ENTRY_TO_VALUE(DATA_ADDR)
#define DATA_FLASH_ADDR     (ENTRY_TO_VALUE(DATA_LADDR) +  BASE_FLASH_ADDR)

#define LOAD_SIZE           ENTRY_TO_VALUE(LOAD_SIZE)

#define STACK_SIZE          ENTRY_TO_VALUE(STACK_SIZE)
#define STACK_RAM_ADDR      ENTRY_TO_VALUE(STACK_ADDR)

#define SRAM1_SIZE          ENTRY_TO_VALUE(SRAM1_SIZE)
#define SRAM1_RAM_ADDR      ENTRY_TO_VALUE(SRAM1_ADDR)
#define SRAM1_FLASH_ADDR    (ENTRY_TO_VALUE(SRAM1_LADDR) +  BASE_FLASH_ADDR)

#define SRAM2_SIZE          ENTRY_TO_VALUE(SRAM2_SIZE)
#define SRAM2_RAM_ADDR      ENTRY_TO_VALUE(SRAM2_ADDR)
#define SRAM2_FLASH_ADDR    (ENTRY_TO_VALUE(SRAM2_LADDR) +  BASE_FLASH_ADDR)

#define PARAM_FLASH_ADDR    ENTRY_TO_VALUE(PARAM_ADDR)

#define BANK_OFFSET         0x00

void norflash_load_code(uint32_t addr_ram, uint32_t addr_flash, uint32_t len);
void load_code_init(void);


#endif

